### ISSUE TITLE
It would be better to have a tutorial on the method of implementing than the source code

### ISSUE THREAD

**Issue by ponyatov** [darkf/parseparse#1]
It would be better to have a tutorial on the method of implementing than the source code.

I'm in search of the method of binary parsing able to parse really complex context-sensitive grammars describes binary (bit-level) data formats and network streams.
https://forum.nim-lang.org/t/5202

Can you suggest some tutorial on using predicates, backtracking and some sort of state machine to do error-resistive binary stream parsing?

**Comment by darkf** [comment]
Well this repo is just a simple, naive backtracking recursive descent parser oriented towards text input streams. 

If you want binary (de)serialization / (un)parsing you'd have to look elsewhere. [Construct](https://construct.readthedocs.io/en/latest/) is interesting, it's a bit like Kaitai except a Python EDSL that supports (I believe) context-sensitive grammars. It handles parsing and unparsing of binary data. 

I'd look there. I don't know what you mean by error-resistive, but it could handle validation as well. 

I'm closing this issue because it's not really relevant. Good luck.
